### PR TITLE
[bootloader] Add loongarch64 support for bootloader

### PR DESCRIPTION
**Pull request by LoongsonHJW**
Let calamares installer add loongarch64 architecture

### CODE REVIEW

**Review by loongson-zn — APPROVED** [review]
ty

**Review by yetist — APPROVED** [review]
LGTM

**Comment by yetist** [comment]
补丁本身没问题，CI没过看起来跟这个补丁内容无关

**Comment by hanjianju** [comment]
LGTM

**Comment by LoongsonHJW** [comment]
> 补丁本身没问题，CI没过看起来跟这个补丁内容无关

错误：
/__w/calamares/calamares/src/modules/webview/WebViewStep.cpp: In constructor 'WebViewStep::WebViewStep(QObject*)':
/__w/calamares/calamares/src/modules/webview/WebViewStep.cpp:35:93: error: 'HighQualityAntialiasing' is not a member of 'QPainter'
看了看编译的错误，CI的编译环境中QPainter类有问题

**Review by hanjianju — APPROVED** [review]

**Review by liuxiang88 — APPROVED** [review]

**Pull request merged**
